name: PayShield Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Server Dependencies
      working-directory: ./src/server
      run: npm install

    - name: Run Server Unit Tests
      working-directory: ./src/server
      run: npm run test

  client-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Client Dependencies
      working-directory: ./src/client
      run: npm install

    - name: Run Client Unit Tests
      working-directory: ./src/client
      run: npm run test
